### ISSUE TITLE
iOS Setup

### ISSUE THREAD

**Issue by xenovector** [abo-el30la/zoom_native_sdk#1]
Hi, just wanna to confirm that the step mentioned "ios you need to darg and drop zoom ios meeting sdk manually to your application", is it drag the downloaded "MobileRTC.xcframework" & "MobileRTCScreenShare.xcframework" in the lib into my flutter's iOS project which open it through ios/runner.workspace? Or are you trying to mean drag and drop at flutter project directory?

Reason I ask this is because my side keep facing the below issue even when I did follow zoom iOS guideline:

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): No such module 'MobileRTC'
/Users/dextergold/flutter/.pub-cache/hosted/pub.dartlang.org/zoom_native_sdk-0.3.2/ios/Classes/SwiftZoomNativeSdkPlugin.swift:2:7

**Comment by abo-el30la** [comment]
you should drag and drop mobile rtc at runner project in xcode and embed it to project
you can follow those instructions -> [IOS Zoom install sdk](https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/getting-started/install-sdk/)

**Comment by mib200** [comment]
Hi @abo-el30la have you successfully run it on iOS? I added Zoom SDK to the zoom_native_sdk plugin iOS folder, and application builds. But as soon as I init the plugin in my app, it crashes, any idea?

**Comment by abo-el30la** [comment]
can you provide the crash log or the error raised?

**Comment by abo-el30la** [comment]
and be sure you are using the latest version.

**Comment by mib200** [comment]
@abo-el30la The MobileRTC framework is not found now. No matter what I do. I am not sure what is breaking this. Can you please try and update the example?

**Comment by AhmedNasser7797** [comment]
any updates about ios setup ?

**Comment by mohammmedsedky** [comment]
now new update is available for ios integration
