### ISSUE TITLE
Help me, it doesn't show the meeting

### ISSUE THREAD

**Issue by angelgoitia** [abo-el30la/zoom_native_sdk#9]
I/flutter (26709): ZoomNatively-initZoom
D/DecorView[](26709): onWindowFocusChanged hasWindowFocus true
I/HandWritingStubImpl(26709): refreshLastKeyboardType: 1
I/HandWritingStubImpl(26709): getCurrentKeyboardType: 1
D/TAG     (26709): onZoomSDKInitializeResult: 0 , 0
I/flutter (26709): ZoomNatively-joinMeting 8748286446
D/TAG     (26709): onMethodCall: {meetingNumber=8748286446, meetingPassword=QkJoVlEwM0toWGsyN1dzTXdsb1BQZz09}
I/flutter (26709): MethodChannelZoomNatively-joinMeting -> true
I/flutter (26709): onLoadStart https://www.mutarelife.work/administrator/rooms/live/NA==
I/GED     (26709): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 31, oppidx_max 31, oppidx_min 0
I/com.mutarelife(26709): NativeAlloc concurrent copying GC freed 54926(2620KB) AllocSpace objects, 181(5140KB) LOS objects, 49% free, 12MB/25MB, paused 491us,82us total 192.273ms
D/BLASTBufferQueue(26709): [VRI[MeetingEndMessageActivity]#6](f:0,a:1) destructor()
D/BufferQueueConsumer(26709): [VRI[MeetingEndMessageActivity]#6(BLAST Consumer)6](id:68550000000c,api:0,p:-1,c:26709) disconnect
D/View    (26709): [Warning] assignParent to null: this = DecorView@864b851[MeetingEndMessageActivity]
D/BLASTBufferQueue(26709): [VRI[MeetingEndMessageActivity]#7](f:0,a:0) destructor()
D/BufferQueueConsumer(26709): [VRI[MeetingEndMessageActivity]#7(BLAST Consumer)7](id:68550000000d,api:0,p:-1,c:26709) disconnect
D/View    (26709): [Warning] assignParent to null: this = DecorView@b952089[MeetingEndMessageActivity]
D/BLASTBufferQueue(26709): [VRI[PopupWindow:ca4f5d9]#3](f:0,a:0) destructor()
D/BufferQueueConsumer(26709): [VRI[PopupWindow:ca4f5d9]#3(BLAST Consumer)3](id:685500000009,api:0,p:-1,c:26709) disconnect
D/View    (26709): [Warning] assignParent to null: this = android.widget.PopupWindow$PopupDecorView{bbfef54 V.E...... R.....ID 0,0-0,2253}
W/Activity(26709): PerfMonitor: Slow Operation: Activity com.mutarelife/com.zipow.videobox.ConfActivityNormal onDestroy took 229ms
D/BLASTBufferQueue(26709): [VRI[ConfActivityNormal]#2](f:0,a:1) destructor()
D/BufferQueueConsumer(26709): [VRI[ConfActivityNormal]#2(BLAST Consumer)2](id:685500000008,api:0,p:-1,c:26709) disconnect
D/View    (26709): [Warning] assignParent to null: this = DecorView@a010c87[ConfActivityNormal]
I/Choreographer(26709): Skipped 60 frames!  The application may be doing too much work on its main thread.
W/Looper  (26709): PerfMonitor doFrame : time=9ms vsyncFrame=0 latency=1012ms procState=-1 historyMsgCount=33 (msgIndex=24 wall=88ms seq=20271 late=266ms h=android.app.ActivityThread$H w=159) (msgIndex=25 wall=634ms seq=20272 late=378ms h=android.app.ActivityThread$H w=159)
I/OpenGLRenderer(26709): Davey! duration=1036ms; Flags=0, FrameTimelineVsyncId=296395308, IntendedVsync=544034937161108, Vsync=544035939245768, InputEventId=0, HandleInputStart=544035950056580, AnimationStart=544035950065503, PerformTraversalsStart=544035952091041, DrawStart=544035955101580, FrameDeadline=544034970529185, FrameInterval=544035949748272, FrameStartTime=16701411, SyncQueued=544035957748887, SyncStart=544035957964272, IssueDrawCommandsStart=544035958088041, SwapBuffers=544035963224887, FrameCompleted=544035973687964, DequeueBufferDuration=47077, QueueBufferDuration=599462, GpuCompleted=544035973687964, SwapBuffersCompleted=544035964921503, DisplayPresentTime=544019754285271, CommandSubmissionCompleted=544035963224887,
W/com.mutarelife(26709): Cleared Reference was only reachable from finalizer (only reported once)
I/com.mutarelife(26709): NativeAlloc concurrent copying GC freed 39211(1625KB) AllocSpace objects, 34(984KB) LOS objects, 49% free, 12MB/24MB, paused 276us,509us total 240.623ms
I/Choreographer(26709): Skipped 38 frames!  The application may be doing too much work on its main thread.
I/flutter (26709): Message coming from the Dart side: To use gallery view on Chrome/Chromium browsers, SharedArrayBuffer is required.
I/flutter (26709):   See for details: https://developers.zoom.us/docs/meeting-sdk/web/gallery-view/
W/Looper  (26709): PerfMonitor doFrame : time=21ms vsyncFrame=0 latency=642ms procState=-1 historyMsgCount=20 (msgIndex=12 wall=60ms seq=20367 late=554ms h=android.os.Handler c=com.zipow.videobox.VideoBoxApplication$s)
D/AudioTrack(26709): start(15734): 0xb400007d825bd000, prior state:STATE_STOPPED
D/AAudio  (26709): AAudioStream_requestStart(s#2) returned 0 ---------
D/com.mutarelife(26709): PlayerBase::setVolume() from IPlayer
D/AAudioStream(26709): setDuckAndMuteVolume() to 1.000000
D/AudioTrack(26709): setVolume(15734): 0xb400007d825bd000, left = 1.000000, right = 1.000000
D/AudioStreamTrack(26709): onAudioDeviceUpdate() audioIo 13 devId 3 => 3
3
W/libc    (26709): Access denied finding property "vendor.camera.aux.packagelist"
D/DecorView[](26709): getWindowModeFromSystem  windowmode is 1
D/DecorView[](26709): updateDecorCaptionStatus windowMode is 1
2
W/libc    (26709): Access denied finding property "vendor.camera.aux.packagelist"
W/Looper  (26709): PerfMonitor doFrame : time=19ms vsyncFrame=0 latency=368ms procState=-1 historyMsgCount=53
3
W/libc    (26709): Access denied finding property "vendor.camera.aux.packagelist"
D/AAudioStream(26709): setState(s#2) from 3 to 4
I/AudioTrack(26709): isLongTimeZeroData zoer date time 1 Seconds
I/flutter (26709): Message coming from the Dart side: pre load wasm success: https://source.zoom.us/2.17.0/lib/av/video.simd.wasm
I/flutter (26709): Message coming from the Dart side: pre load wasm success: https://source.zoom.us/2.17.0/lib/av/audio.encode.wasm
I/AudioTrack(26709): isLongTimeZeroData zoer date time 2 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 3 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 4 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 5 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 6 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 7 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 8 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 9 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 10 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 11 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 12 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 13 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 14 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 15 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 16 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 17 Seconds

I/AudioTrack(26709): isLongTimeZeroData zoer date time 18 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 19 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 20 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 21 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 22 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 23 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 24 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 25 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 26 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 27 Seconds
I/AudioTrack(26709): isLongTimeZeroData zoer date time 28 Seconds
D/AAudio  (26709): AAudioStream_requestStop(s#2) called
D/AAudioStream(26709): setState(s#2) from 4 to 9
D/AudioTrack(26709): stop(15734): 0xb400007d825bd000, prior state:STATE_ACTIVE
D/AudioTrackShared(26709): this(0xb400007d82ec9f80), mCblk(0x7e3339e000), front(1447168), mIsOut 1, interrupt() FUTEX_WAKE
D/AudioTrack(26709): stop(15734): 0xb400007d825bd000 stop done
D/AAudioStream(26709): setState(s#2) from 9 to 10
D/AAudio  (26709): AAudioStream_requestStop(s#2) called
D/AAudio  (26709): AAudioStream_close(s#2) called ---------------
D/AAudioStream(26709): setState(s#2) from 10 to 11
D/AudioTrack(26709): stop(15734): 0xb400007d825bd000, prior state:STATE_STOPPED
D/AudioTrackShared(26709): this(0xb400007d82ec9f80), mCblk(0x7e3339e000), front(1447680), mIsOut 1, interrupt() FUTEX_WAKE
D/AudioTrack(26709): ~AudioTrack(15734): 0xb400007d825bd000
D/AudioTrack(26709): stop(15734): 0xb400007d825bd000, prior state:STATE_STOPPED
D/AAudioStream(26709): setState(s#2) from 11 to 12
D/AAudioStream(26709): ~AudioStream(s#2) mPlayerBase strongCount = 2
D/AAudio  (26709): AAudioStream_close(s#2) returned 0 ---------

It doesn't show the meeting, my phone has a black screen but it's big because I can scroll horizontally and vertically.

How do I do that if there is a problem I want it to open a widget

**Comment by angelgoitia** [comment]
o Meeting not starting, it starts loading but then exits

**Comment by angelgoitia** [comment]
try {
      final _zoomNativelyPlugin = ZoomNativeSdk();

      if (!isInitialized.value) {
        isInitialized.value = (await _zoomNativelyPlugin.initZoom(
              appKey: appKey,
              appSecret: appSecret,
            )) ??
            false;
      }

      if (isInitialized.value) {
        await _zoomNativelyPlugin.joinMeting(
          meetingNumber: meetingId.value,
          meetingPassword: meetingPass.value,
        );
      }
    } on PlatformException catch (e) {
      print("error");
      print(e.message);
    }
    
permission :
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
    
    it appears entering a meeting then it is removed it exits loading from zoom and it is still on my website
    
    Console:
    I/flutter (17183): entro joinMeeting
I/flutter (17183): ZoomNatively-initZoom
D/DecorView[](17183): onWindowFocusChanged hasWindowFocus false
D/TAG     (17183): onZoomSDKInitializeResult: 0 , 0
I/flutter (17183): ZoomNatively-joinMeting 8748286446
D/DecorView[](17183): onWindowFocusChanged hasWindowFocus true
I/HandWritingStubImpl(17183): refreshLastKeyboardType: 1
I/HandWritingStubImpl(17183): getCurrentKeyboardType: 1
D/TAG     (17183): onMethodCall: {meetingNumber=8748286446, meetingPassword=QkJoVlEwM0toWGsyN1dzTXdsb1BQZz09}
I/flutter (17183): MethodChannelZoomNatively-joinMeting -> true
D/BLASTBufferQueue(17183): [VRI[MeetingEndMessageActivity]#7](f:0,a:1) destructor()
D/BufferQueueConsumer(17183): [VRI[MeetingEndMessageActivity]#7(BLAST Consumer)7](id:431f0000000d,api:0,p:-1,c:17183) disconnect
D/View    (17183): [Warning] assignParent to null: this = DecorView@729bb12[MeetingEndMessageActivity]
D/BLASTBufferQueue(17183): [VRI[MeetingEndMessageActivity]#8](f:0,a:0) destructor()
D/BufferQueueConsumer(17183): [VRI[MeetingEndMessageActivity]#8(BLAST Consumer)8](id:431f0000000e,api:0,p:-1,c:17183) disconnect
D/View    (17183): [Warning] assignParent to null: this = DecorView@ffd9a6a[MeetingEndMessageActivity]
W/com.mutarelife(17183): Cleared Reference was only reachable from finalizer (only reported once)
2
D/AAudio  (17183): AAudioStream_requestStop(s#2) called
2
E/GPUAUX  (17183): [AUX]GuiExtAuxCheckAuxPath:667: Null anb
D/AAudio  (17183): AAudioStream_close(s#2) called ---------------
D/AAudioStream(17183): setState(s#2) from 10 to 11
D/AudioTrack(17183): stop(16533): 0xb400007cdcf5aa00, prior state:STATE_STOPPED
D/AudioTrackShared(17183): this(0xb400007d82eb9b80), mCblk(0x7e334fc000), front(512), mIsOut 1, interrupt() FUTEX_WAKE
D/AudioTrack(17183): ~AudioTrack(16533): 0xb400007cdcf5aa00
D/AudioTrack(17183): stop(16533): 0xb400007cdcf5aa00, prior state:STATE_STOPPED
D/AAudioStream(17183): setState(s#2) from 11 to 12
D/AAudioStream(17183): ~AudioStream(s#2) mPlayerBase strongCount = 2
D/AAudio  (17183): AAudioStream_close(s#2) returned 0 ---------

**Comment by vaibhav936** [comment]
https://github.com/abo-el30la/zoom_native_sdk/issues/8

watch this
